version: "3.8"
services:
  flask:
    image: 127.0.0.1:5000/flask-app
    build: .
    environment:
      PORT: 4000
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_HOST: pg
    ports:
      - "4000:4000"

  pg:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password
